version: '3'

services:
    jobbag_api:
        image: plmarcelo/docker_php71
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        links:
            - jobbag_db
        working_dir: /var/www/html
        env_file: .env
        container_name: jobbag_api

    jobbag_db:
        image: mysql:5.7
        ports:
            - 3310:3306
        volumes:
            - ${PATH_DB_DATA}:/var/lib/mysql
        env_file: .env
        container_name: jobbag_db
