authentication:
    resource: ../../src/JobBag/Controller
    type: annotation

public_services:
    resource: ../../src/JobBag/Controller/Pub
    type: annotation
    prefix:
        en: 'pub/{version<v[1]>?1}' # don't prefix URLs for English, the default locale
        es: 'pub/{version<v[1]>?1}/es'
        fr: 'pub/{version<v[1]>?1}/fr'

private_services:
    resource: ../../src/JobBag/Controller/Prv
    type: annotation
    prefix:
        en: 'prv/{version<v[1]>?1}' # don't prefix URLs for English, the default locale
        es: 'prv/{version<v[1]>?1}/es'
        fr: 'prv/{version<v[1]>?1}/fr'
