# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the api is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    default_locale: en

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    JobBag\:
        resource: '../src/JobBag/*'
        exclude: '../src/JobBag/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    JobBag\Controller\:
        resource: '../src/JobBag/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    JobBag\Application\Location\FetchLocationsList:
        arguments:
            $defaultLocale: '%default_locale%'

    JobBag\Application\Profession\FetchProfessionsList:
        arguments:
            $defaultLocale: '%default_locale%'

    JobBag\Application\Scholarship\FetchScholarshipsList:
        arguments:
            $defaultLocale: '%default_locale%'

    jobbag.denormalizer.employee:
        class: 'JobBag\Infrastructure\Service\Serializer\Normalizer\EmployeeDenormalizer'
        public: false
        tags: [serializer.denormalizer]

    jobbag.denormalizer.person:
        class: 'JobBag\Infrastructure\Service\Serializer\Normalizer\PersonDenormalizer'
        public: false
        tags: [serializer.denormalizer]

#    jobabg.serializer.default:
#        class: 'Symfony\Component\Serializer\Serializer'
#        arguments:
#            0:
#            - '@jobbag.denormalizer.employee'
#            - '@serializer.denormalizer.object'
#            1:
#            - '@acme.encoder.json'
